project:
  type: website

website:
  title: "Visual Analytics & Application "
  navbar:
    left: 
      - href: home.qmd
        text: Home
      - text: "Hands-on Exercises"
        menu: 
          - href: exercise1.qmd
            text: Exercise 1

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

